# Install dependencies only when needed
FROM node:16-alpine AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install

ENV NODE_ENV development

EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "dev"]