version: '3.7'
services:
  frontend:
    depends_on:
      - backend
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - '3000:3000'
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.rule=Host("frontend.docker.localhost")
    volumes:
      - ./frontend:/app/
      - /app/node_modules
      - /app/.next

  backend:
    depends_on:
      - redis
      - postgres
    build:
      context: backend/pingService
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '4000:4000'
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.rule=Host("backend.docker.localhost")

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=redis

    ports:
      - '6379:6379'
    labels:
      - traefik.enable=true

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5422:5432'
    labels:
      - traefik.enable=true
